<a href="https://colab.research.google.com/github/jcdumlao14/Homework-ml-zoomcamp/blob/main/01_Homework_ml_zoomcamp_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ml-zoomcamp-2022: Homework-1**

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline


# **Question 1**

What's the version of NumPy that you installed?

You can get the version information using the __version__ field:

In [13]:
print("My Answer is:", np.__version__)

My Answer is: 1.21.6


# **Question 2**

How many records are in the dataset?

Here you need to specify the number of rows.

* 16
* 6572
* 11914 
* 18990

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')
len(df)

11914

In [10]:
df.shape
print("My Answer is:",11914)

My Answer is: 11914


# **Question 3**

Who are the most frequent car manufacturers (top-3) according to the dataset?

* Chevrolet, Volkswagen, Toyota
* Chevrolet, Ford, Toyota
* Ford, Volkswagen, Toyota
* Chevrolet, Ford, Volkswagen


In [5]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
df["Make"].value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Answer:  Chevrolet, Ford, Volkswagen

# **Question 4**

What's the number of unique Audi car models in the dataset?

* 3
* 16 
* 26
* 34 

In [9]:
print("My Answer is:",df[df['Make'] == 'Audi']['Model'].nunique())

My Answer is: 34


# **Question 5**

How many columns in the dataset have missing values?

* 5 
* 6
* 7
* 8



In [14]:
columns_with_nan = df.columns[df.isna().any()].to_list()
print(f"Columns with missing values:{columns_with_nan}")
print(f"Number of columns with missing values : is the Answer = {len(columns_with_nan)}")


Columns with missing values:['Engine Fuel Type', 'Engine HP', 'Engine Cylinders', 'Number of Doors', 'Market Category']
Number of columns with missing values : is the Answer = 5


# **Question 6**

1. Find the median value of "Engine Cylinders" column in the dataset.
Next, calculate the most frequent value of the same "Engine Cylinders".

2. Use the fillna method to fill the missing values in "Engine 

3. Cylinders" with the most frequent value from the previous step.

4. Now, calculate the median value of "Engine Cylinders" once again.
Has it changed?

Hint: refer to existing mode and median functions to complete the task.

* Yes
* No

### 1. Find the median value of "Engine Cylinders" column in the dataset. Next, calculate the most frequent value of the same "Engine Cylinders"

In [15]:
df["Engine Cylinders"].median()

6.0

### 1.1 Next, calculate the most frequent value of the same "Engine Cylinders"

In [17]:
df["Engine Cylinders"].mode()

0    4.0
dtype: float64

### 2. Use the fillna method to fill the missing values in "Engine Cylinders"

In [19]:
df["Engine Cylinders"].fillna(float(df["Engine Cylinders"].mode()),inplace = True)

In [20]:
df["Engine Cylinders"].isna().value_counts()

False    11914
Name: Engine Cylinders, dtype: int64

### 4. Now, calculate the median value of "Engine Cylinders" once again. Has it changed?



In [21]:
df["Engine Cylinders"].median()

6.0

Answer: No, their no changes

# **Question 7**

1. Select all the "Lotus" cars from the dataset.

2. Select only columns "Engine HP", "Engine Cylinders".

3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

4. Get the underlying NumPy array. Let's call it X.

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

6. Invert XTX.

7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

9. What's the value of the first element of w?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

* -0.0723
* 4.5949
* 31.6537
* 63.5643

### 1. Select all the "Lotus" cars from the dataset.

In [23]:
lotus_cars = df[df["Make"]== 'Lotus']
lotus_cars

Make      Model  Year                Engine Fuel Type  Engine HP  \
3912  Lotus      Elise  2009     premium unleaded (required)      189.0   
3913  Lotus      Elise  2009     premium unleaded (required)      218.0   
3914  Lotus      Elise  2009     premium unleaded (required)      189.0   
3915  Lotus      Elise  2010     premium unleaded (required)      189.0   
3916  Lotus      Elise  2010     premium unleaded (required)      218.0   
3917  Lotus      Elise  2011     premium unleaded (required)      189.0   
3918  Lotus      Elise  2011     premium unleaded (required)      217.0   
3919  Lotus      Elise  2011     premium unleaded (required)      217.0   
4216  Lotus     Esprit  2002     premium unleaded (required)      350.0   
4217  Lotus     Esprit  2003     premium unleaded (required)      350.0   
4218  Lotus     Esprit  2004     premium unleaded (required)      350.0   
4257  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4258  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4259  Lotus      Evora  2011     premium unleaded (required)      276.0   
4260  Lotus      Evora  2011     premium unleaded (required)      276.0   
4261  Lotus      Evora  2013     premium unleaded (required)      276.0   
4262  Lotus      Evora  2013     premium unleaded (required)      345.0   
4263  Lotus      Evora  2013     premium unleaded (required)      345.0   
4264  Lotus      Evora  2013     premium unleaded (required)      276.0   
4265  Lotus      Evora  2014     premium unleaded (required)      345.0   
4266  Lotus      Evora  2014     premium unleaded (required)      276.0   
4267  Lotus      Evora  2014     premium unleaded (required)      345.0   
4268  Lotus      Evora  2014     premium unleaded (required)      276.0   
4292  Lotus      Exige  2009  premium unleaded (recommended)      257.0   
4293  Lotus      Exige  2009  premium unleaded (recommended)      240.0   
4294  Lotus      Exige  2010  premium unleaded (recommended)      240.0   
4295  Lotus      Exige  2011  premium unleaded (recommended)      240.0   
4296  Lotus      Exige  2011  premium unleaded (recommended)      257.0   
4297  Lotus      Exige  2011  premium unleaded (recommended)      257.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   
3917               4.0            MANUAL  rear wheel drive              2.0   
3918               4.0            MANUAL  rear wheel drive              2.0   
3919               4.0            MANUAL  rear wheel drive              2.0   
4216               8.0            MANUAL  rear wheel drive              2.0   
4217               8.0            MANUAL  rear wheel drive              2.0   
4218               8.0            MANUAL  rear wheel drive              2.0   
4257               6.0            MANUAL  rear wheel drive              2.0   
4258               6.0            MANUAL  rear wheel drive              2.0   
4259               6.0            MANUAL  rear wheel drive              2.0   
4260               6.0            MANUAL  rear wheel drive              2.0   
4261               6.0            MANUAL  rear wheel drive              2.0   
4262               6.0            MANUAL  rear wheel drive              2.0   
4263               6.0            MANUAL  rear wheel drive              2.0   
4264               6.0            MANUAL  rear wheel drive              2.0   
4265               6.0            MANUAL  rear wheel drive              2.0   
4266               6.0            MANUAL  rear wheel drive              2.0   
4267              

### 2. Select only columns "Engine HP", "Engine Cylinders".

In [25]:
select_columns = lotus_cars[["Engine HP", "Engine Cylinders"]]
select_columns

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

### 3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

In [27]:
select_columns = select_columns.drop_duplicates()
select_columns

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [28]:
#check the dataframe with 9 rows
select_columns.shape

(9, 2)

### 4. Get the underlying NumPy array. Let's call it X.



In [29]:
X = select_columns.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

### 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [30]:
#To get the transpose of X
XT = X.T
XT

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [31]:
#Use X.T.,let's call the result XTX by Multiply X with XT
XTX = np.dot(XT,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

### 6. Invert XTX.

In [32]:
XTXI = np.linalg.inv(XTX)
XTXI

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

### 7.  Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

In [34]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

### 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.



In [39]:
W = np.dot(np.dot(XTXI,XT), y)


### 9. What's the value of the first element of w?

In [38]:
W

array([  4.59494481, -63.56432501])

Answer: 4.59494481

**JCD!**